name: Lint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: GitHub Action for Yarn
      uses: Borales/actions-yarn@v2.1.0
      with:
        cmd: install
    - name: GitHub Action for Yarn
      uses: Borales/actions-yarn@v2.1.0
      with:
        cmd: lint
